# Generated by Django 4.2 on 2023-05-19 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=40)),
                ('line1', models.CharField(blank=True, default='main', max_length=150, null=True)),
                ('line2', models.CharField(blank=True, default='main', max_length=150, null=True)),
                ('line3', models.CharField(blank=True, default='main', max_length=150, null=True)),
                ('line4', models.CharField(blank=True, default='main', max_length=150, null=True)),
                ('description', models.CharField(blank=True, default='main', max_length=200, null=True)),
                ('unit_price', models.IntegerField(blank=True, default=1, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line1', models.CharField(max_length=150)),
                ('line2', models.CharField(max_length=150)),
                ('line3', models.CharField(max_length=150)),
                ('line4', models.CharField(max_length=150)),
                ('urlname', models.CharField(blank=True, max_length=150, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Invoicenumber', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('invoicedate', models.DateField(blank=True, null=True)),
                ('rangemin', models.FloatField(blank=True, null=True)),
                ('rangemax', models.FloatField(blank=True, null=True)),
                ('head_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelapp.headcompany')),
            ],
        ),
        migrations.CreateModel(
            name='SplitCompnay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(blank=True, null=True)),
                ('drop_time', models.TimeField(blank=True, null=True)),
                ('vehicle', models.CharField(max_length=100)),
                ('drop', models.IntegerField()),
                ('weight', models.FloatField()),
                ('status', models.BooleanField(default=False, max_length=100)),
                ('sub_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelapp.subcompany')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousDataSubCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line1', models.CharField(max_length=150)),
                ('line2', models.CharField(max_length=150)),
                ('line3', models.CharField(max_length=150)),
                ('line4', models.CharField(max_length=150)),
                ('urlname', models.CharField(blank=True, max_length=150, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Invoicenumber', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('invoicedate', models.DateField(blank=True, null=True)),
                ('rangemin', models.FloatField(blank=True, null=True)),
                ('rangemax', models.FloatField(blank=True, null=True)),
                ('head_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelapp.headcompany')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line1', models.CharField(max_length=150)),
                ('line2', models.CharField(max_length=150)),
                ('line3', models.CharField(max_length=150)),
                ('line4', models.CharField(max_length=150)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('Invoicenumber', models.IntegerField(blank=True, null=True)),
                ('urlname', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('invoicedate', models.DateField(blank=True, null=True)),
                ('rangemin', models.FloatField(blank=True, null=True)),
                ('rangemax', models.FloatField(blank=True, null=True)),
                ('head_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelapp.headcompany')),
            ],
        ),
    ]
