# Generated by Django 4.2 on 2023-04-18 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SubCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line1', models.CharField(max_length=150)),
                ('line2', models.CharField(max_length=150)),
                ('line3', models.CharField(max_length=150)),
                ('line4', models.CharField(max_length=150)),
                ('weight', models.IntegerField()),
                ('Invoicenumber', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('invoicedate', models.DateField()),
                ('head_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelapp.headcompany')),
            ],
        ),
    ]
