# Generated by Django 4.2 on 2023-05-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousdatasubcompany',
            name='nyid',
            field=models.IntegerField(default=1),
        ),
    ]
