# Generated by Django 4.2 on 2023-04-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0002_alter_subcompany_invoicenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headcompany',
            name='line1',
            field=models.CharField(blank=True, default='main', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='headcompany',
            name='line2',
            field=models.CharField(blank=True, default='main', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='headcompany',
            name='line3',
            field=models.CharField(blank=True, default='main', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='headcompany',
            name='line4',
            field=models.CharField(blank=True, default='main', max_length=150, null=True),
        ),
    ]
