# Generated by Django 4.2 on 2023-05-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0002_previousdatasubcompany_nyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previousdatasubcompany',
            old_name='nyid',
            new_name='myid',
        ),
    ]
