# Generated by Django 4.2 on 2023-04-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0003_headcompany_line1_headcompany_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headcompany',
            name='description',
            field=models.CharField(blank=True, default='main', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='headcompany',
            name='unit_price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line1', models.CharField(max_length=150)),
                ('line2', models.CharField(max_length=150)),
                ('line3', models.CharField(max_length=150)),
                ('line4', models.CharField(max_length=150)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('Invoicenumber', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('invoicedate', models.DateField(blank=True, null=True)),
                ('head_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelapp.headcompany')),
            ],
        ),
    ]
