# Generated by Django 4.2 on 2023-04-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0004_headcompany_description_headcompany_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headcompany',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
