# Generated by Django 4.2 on 2023-05-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0004_previousdataclientcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcompany',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
