# Generated by Django 4.2 on 2023-04-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0005_headcompany_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitCompnay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(blank=True, null=True)),
                ('drop_time', models.TimeField(blank=True, null=True)),
                ('vehicle', models.CharField(max_length=100)),
                ('drop', models.IntegerField()),
                ('weight', models.FloatField()),
                ('sub_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelapp.subcompany')),
            ],
        ),
    ]
