# Generated by Django 4.2 on 2023-04-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0006_splitcompnay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitcompnay',
            name='sub_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelapp.subcompany', unique=True),
        ),
    ]
