# Generated by Django 4.2 on 2023-04-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0007_alter_splitcompnay_sub_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitcompnay',
            name='sub_company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='excelapp.subcompany'),
        ),
    ]
