# Generated by Django 4.2 on 2023-04-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0008_alter_splitcompnay_sub_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitcompnay',
            name='status',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='splitcompnay',
            name='sub_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelapp.subcompany'),
        ),
    ]
