# Generated by Django 4.2 on 2023-04-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0009_splitcompnay_status_alter_splitcompnay_sub_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitcompnay',
            name='status',
            field=models.BooleanField(default=False, max_length=100),
        ),
    ]
