# Generated by Django 4.2 on 2023-05-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0010_alter_splitcompnay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcompany',
            name='rangemax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcompany',
            name='rangemin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
