# Generated by Django 4.2 on 2023-05-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0011_subcompany_rangemax_subcompany_rangemin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcompany',
            name='rangemax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='rangemin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
