# Generated by Django 4.2 on 2023-05-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0012_clientcompany_rangemax_clientcompany_rangemin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headcompany',
            name='image',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
