# Generated by Django 4.2 on 2023-05-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0013_alter_headcompany_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headcompany',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
