# Generated by Django 4.2 on 2023-05-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0014_alter_headcompany_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcompany',
            name='urlname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
