# Generated by Django 4.2 on 2023-05-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0017_alter_subcompany_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcompany',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
